/**
 * Auto-generated by scripts/download-scryfall.ts
 * Contains card data chunk filenames for client loading
 */

export const CARD_CHUNKS = [
	"cards-000.json",
	"cards-001.json",
	"cards-002.json",
	"cards-003.json",
	"cards-004.json",
	"cards-005.json",
	"cards-006.json",
	"cards-007.json",
	"cards-008.json",
] as const;
