/**
 * Auto-generated by scripts/download-scryfall.ts
 *
 * Files in /data/cards/ have content hashes in filenames for immutable caching.
 * This subfolder is configured for aggressive edge caching via Cloudflare rules
 * (TanStack Start doesn't support custom cache headers).
 */

export const CARD_INDEXES = "indexes-2436e5c6f79396f5.json";

export const CARD_CHUNKS = [
	"cards-000-c370c4bbdf50febf.json",
	"cards-001-de071126cc0bff27.json",
	"cards-002-cc774c9e7a1875ef.json",
	"cards-003-c2a08adf3f90d2e1.json",
	"cards-004-e29c370de8d4c8b0.json",
	"cards-005-448405e66327dc1e.json",
	"cards-006-1a65ecd2f30c3a4e.json",
	"cards-007-9043095f08f5e094.json",
] as const;
