/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ComponentsIndexRouteImport } from './routes/components/index'
import { Route as CardsIndexRouteImport } from './routes/cards/index'
import { Route as UHandleRouteImport } from './routes/u/$handle'
import { Route as OauthCallbackRouteImport } from './routes/oauth/callback'
import { Route as DeckNewRouteImport } from './routes/deck/new'
import { Route as ComponentsCardWireframeRouteImport } from './routes/components/card-wireframe'
import { Route as CardIdRouteImport } from './routes/card/$id'
import { Route as ProfileDidIndexRouteImport } from './routes/profile/$did/index'
import { Route as ComponentsWireframeIdRouteImport } from './routes/components/wireframe.$id'
import { Route as ProfileDidDeckRkeyRouteImport } from './routes/profile/$did/deck/$rkey'
import { Route as ProfileDidDeckRkeyIndexRouteImport } from './routes/profile/$did/deck/$rkey/index'
import { Route as ProfileDidDeckRkeyBulkEditRouteImport } from './routes/profile/$did/deck/$rkey/bulk-edit'

const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsIndexRoute = ComponentsIndexRouteImport.update({
  id: '/components/',
  path: '/components/',
  getParentRoute: () => rootRouteImport,
} as any)
const CardsIndexRoute = CardsIndexRouteImport.update({
  id: '/cards/',
  path: '/cards/',
  getParentRoute: () => rootRouteImport,
} as any)
const UHandleRoute = UHandleRouteImport.update({
  id: '/u/$handle',
  path: '/u/$handle',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthCallbackRoute = OauthCallbackRouteImport.update({
  id: '/oauth/callback',
  path: '/oauth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const DeckNewRoute = DeckNewRouteImport.update({
  id: '/deck/new',
  path: '/deck/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsCardWireframeRoute = ComponentsCardWireframeRouteImport.update({
  id: '/components/card-wireframe',
  path: '/components/card-wireframe',
  getParentRoute: () => rootRouteImport,
} as any)
const CardIdRoute = CardIdRouteImport.update({
  id: '/card/$id',
  path: '/card/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileDidIndexRoute = ProfileDidIndexRouteImport.update({
  id: '/profile/$did/',
  path: '/profile/$did/',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsWireframeIdRoute = ComponentsWireframeIdRouteImport.update({
  id: '/components/wireframe/$id',
  path: '/components/wireframe/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileDidDeckRkeyRoute = ProfileDidDeckRkeyRouteImport.update({
  id: '/profile/$did/deck/$rkey',
  path: '/profile/$did/deck/$rkey',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileDidDeckRkeyIndexRoute = ProfileDidDeckRkeyIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProfileDidDeckRkeyRoute,
} as any)
const ProfileDidDeckRkeyBulkEditRoute =
  ProfileDidDeckRkeyBulkEditRouteImport.update({
    id: '/bulk-edit',
    path: '/bulk-edit',
    getParentRoute: () => ProfileDidDeckRkeyRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/signin': typeof SigninRoute
  '/card/$id': typeof CardIdRoute
  '/components/card-wireframe': typeof ComponentsCardWireframeRoute
  '/deck/new': typeof DeckNewRoute
  '/oauth/callback': typeof OauthCallbackRoute
  '/u/$handle': typeof UHandleRoute
  '/cards': typeof CardsIndexRoute
  '/components': typeof ComponentsIndexRoute
  '/components/wireframe/$id': typeof ComponentsWireframeIdRoute
  '/profile/$did': typeof ProfileDidIndexRoute
  '/profile/$did/deck/$rkey': typeof ProfileDidDeckRkeyRouteWithChildren
  '/profile/$did/deck/$rkey/bulk-edit': typeof ProfileDidDeckRkeyBulkEditRoute
  '/profile/$did/deck/$rkey/': typeof ProfileDidDeckRkeyIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/signin': typeof SigninRoute
  '/card/$id': typeof CardIdRoute
  '/components/card-wireframe': typeof ComponentsCardWireframeRoute
  '/deck/new': typeof DeckNewRoute
  '/oauth/callback': typeof OauthCallbackRoute
  '/u/$handle': typeof UHandleRoute
  '/cards': typeof CardsIndexRoute
  '/components': typeof ComponentsIndexRoute
  '/components/wireframe/$id': typeof ComponentsWireframeIdRoute
  '/profile/$did': typeof ProfileDidIndexRoute
  '/profile/$did/deck/$rkey/bulk-edit': typeof ProfileDidDeckRkeyBulkEditRoute
  '/profile/$did/deck/$rkey': typeof ProfileDidDeckRkeyIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/signin': typeof SigninRoute
  '/card/$id': typeof CardIdRoute
  '/components/card-wireframe': typeof ComponentsCardWireframeRoute
  '/deck/new': typeof DeckNewRoute
  '/oauth/callback': typeof OauthCallbackRoute
  '/u/$handle': typeof UHandleRoute
  '/cards/': typeof CardsIndexRoute
  '/components/': typeof ComponentsIndexRoute
  '/components/wireframe/$id': typeof ComponentsWireframeIdRoute
  '/profile/$did/': typeof ProfileDidIndexRoute
  '/profile/$did/deck/$rkey': typeof ProfileDidDeckRkeyRouteWithChildren
  '/profile/$did/deck/$rkey/bulk-edit': typeof ProfileDidDeckRkeyBulkEditRoute
  '/profile/$did/deck/$rkey/': typeof ProfileDidDeckRkeyIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/signin'
    | '/card/$id'
    | '/components/card-wireframe'
    | '/deck/new'
    | '/oauth/callback'
    | '/u/$handle'
    | '/cards'
    | '/components'
    | '/components/wireframe/$id'
    | '/profile/$did'
    | '/profile/$did/deck/$rkey'
    | '/profile/$did/deck/$rkey/bulk-edit'
    | '/profile/$did/deck/$rkey/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/signin'
    | '/card/$id'
    | '/components/card-wireframe'
    | '/deck/new'
    | '/oauth/callback'
    | '/u/$handle'
    | '/cards'
    | '/components'
    | '/components/wireframe/$id'
    | '/profile/$did'
    | '/profile/$did/deck/$rkey/bulk-edit'
    | '/profile/$did/deck/$rkey'
  id:
    | '__root__'
    | '/'
    | '/signin'
    | '/card/$id'
    | '/components/card-wireframe'
    | '/deck/new'
    | '/oauth/callback'
    | '/u/$handle'
    | '/cards/'
    | '/components/'
    | '/components/wireframe/$id'
    | '/profile/$did/'
    | '/profile/$did/deck/$rkey'
    | '/profile/$did/deck/$rkey/bulk-edit'
    | '/profile/$did/deck/$rkey/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SigninRoute: typeof SigninRoute
  CardIdRoute: typeof CardIdRoute
  ComponentsCardWireframeRoute: typeof ComponentsCardWireframeRoute
  DeckNewRoute: typeof DeckNewRoute
  OauthCallbackRoute: typeof OauthCallbackRoute
  UHandleRoute: typeof UHandleRoute
  CardsIndexRoute: typeof CardsIndexRoute
  ComponentsIndexRoute: typeof ComponentsIndexRoute
  ComponentsWireframeIdRoute: typeof ComponentsWireframeIdRoute
  ProfileDidIndexRoute: typeof ProfileDidIndexRoute
  ProfileDidDeckRkeyRoute: typeof ProfileDidDeckRkeyRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/': {
      id: '/components/'
      path: '/components'
      fullPath: '/components'
      preLoaderRoute: typeof ComponentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cards/': {
      id: '/cards/'
      path: '/cards'
      fullPath: '/cards'
      preLoaderRoute: typeof CardsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$handle': {
      id: '/u/$handle'
      path: '/u/$handle'
      fullPath: '/u/$handle'
      preLoaderRoute: typeof UHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth/callback': {
      id: '/oauth/callback'
      path: '/oauth/callback'
      fullPath: '/oauth/callback'
      preLoaderRoute: typeof OauthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deck/new': {
      id: '/deck/new'
      path: '/deck/new'
      fullPath: '/deck/new'
      preLoaderRoute: typeof DeckNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/card-wireframe': {
      id: '/components/card-wireframe'
      path: '/components/card-wireframe'
      fullPath: '/components/card-wireframe'
      preLoaderRoute: typeof ComponentsCardWireframeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/card/$id': {
      id: '/card/$id'
      path: '/card/$id'
      fullPath: '/card/$id'
      preLoaderRoute: typeof CardIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/$did/': {
      id: '/profile/$did/'
      path: '/profile/$did'
      fullPath: '/profile/$did'
      preLoaderRoute: typeof ProfileDidIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/wireframe/$id': {
      id: '/components/wireframe/$id'
      path: '/components/wireframe/$id'
      fullPath: '/components/wireframe/$id'
      preLoaderRoute: typeof ComponentsWireframeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/$did/deck/$rkey': {
      id: '/profile/$did/deck/$rkey'
      path: '/profile/$did/deck/$rkey'
      fullPath: '/profile/$did/deck/$rkey'
      preLoaderRoute: typeof ProfileDidDeckRkeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/$did/deck/$rkey/': {
      id: '/profile/$did/deck/$rkey/'
      path: '/'
      fullPath: '/profile/$did/deck/$rkey/'
      preLoaderRoute: typeof ProfileDidDeckRkeyIndexRouteImport
      parentRoute: typeof ProfileDidDeckRkeyRoute
    }
    '/profile/$did/deck/$rkey/bulk-edit': {
      id: '/profile/$did/deck/$rkey/bulk-edit'
      path: '/bulk-edit'
      fullPath: '/profile/$did/deck/$rkey/bulk-edit'
      preLoaderRoute: typeof ProfileDidDeckRkeyBulkEditRouteImport
      parentRoute: typeof ProfileDidDeckRkeyRoute
    }
  }
}

interface ProfileDidDeckRkeyRouteChildren {
  ProfileDidDeckRkeyBulkEditRoute: typeof ProfileDidDeckRkeyBulkEditRoute
  ProfileDidDeckRkeyIndexRoute: typeof ProfileDidDeckRkeyIndexRoute
}

const ProfileDidDeckRkeyRouteChildren: ProfileDidDeckRkeyRouteChildren = {
  ProfileDidDeckRkeyBulkEditRoute: ProfileDidDeckRkeyBulkEditRoute,
  ProfileDidDeckRkeyIndexRoute: ProfileDidDeckRkeyIndexRoute,
}

const ProfileDidDeckRkeyRouteWithChildren =
  ProfileDidDeckRkeyRoute._addFileChildren(ProfileDidDeckRkeyRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SigninRoute: SigninRoute,
  CardIdRoute: CardIdRoute,
  ComponentsCardWireframeRoute: ComponentsCardWireframeRoute,
  DeckNewRoute: DeckNewRoute,
  OauthCallbackRoute: OauthCallbackRoute,
  UHandleRoute: UHandleRoute,
  CardsIndexRoute: CardsIndexRoute,
  ComponentsIndexRoute: ComponentsIndexRoute,
  ComponentsWireframeIdRoute: ComponentsWireframeIdRoute,
  ProfileDidIndexRoute: ProfileDidIndexRoute,
  ProfileDidDeckRkeyRoute: ProfileDidDeckRkeyRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
