/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CardsIndexRouteImport } from './routes/cards/index'
import { Route as CardsOracleIdRouteImport } from './routes/cards/$oracleId'
import { Route as CardsOracleIdScryfallIdRouteImport } from './routes/cards/$oracleId/$scryfallId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CardsIndexRoute = CardsIndexRouteImport.update({
  id: '/cards/',
  path: '/cards/',
  getParentRoute: () => rootRouteImport,
} as any)
const CardsOracleIdRoute = CardsOracleIdRouteImport.update({
  id: '/cards/$oracleId',
  path: '/cards/$oracleId',
  getParentRoute: () => rootRouteImport,
} as any)
const CardsOracleIdScryfallIdRoute = CardsOracleIdScryfallIdRouteImport.update({
  id: '/$scryfallId',
  path: '/$scryfallId',
  getParentRoute: () => CardsOracleIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cards/$oracleId': typeof CardsOracleIdRouteWithChildren
  '/cards': typeof CardsIndexRoute
  '/cards/$oracleId/$scryfallId': typeof CardsOracleIdScryfallIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cards/$oracleId': typeof CardsOracleIdRouteWithChildren
  '/cards': typeof CardsIndexRoute
  '/cards/$oracleId/$scryfallId': typeof CardsOracleIdScryfallIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cards/$oracleId': typeof CardsOracleIdRouteWithChildren
  '/cards/': typeof CardsIndexRoute
  '/cards/$oracleId/$scryfallId': typeof CardsOracleIdScryfallIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cards/$oracleId'
    | '/cards'
    | '/cards/$oracleId/$scryfallId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/cards/$oracleId' | '/cards' | '/cards/$oracleId/$scryfallId'
  id:
    | '__root__'
    | '/'
    | '/cards/$oracleId'
    | '/cards/'
    | '/cards/$oracleId/$scryfallId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CardsOracleIdRoute: typeof CardsOracleIdRouteWithChildren
  CardsIndexRoute: typeof CardsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cards/': {
      id: '/cards/'
      path: '/cards'
      fullPath: '/cards'
      preLoaderRoute: typeof CardsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cards/$oracleId': {
      id: '/cards/$oracleId'
      path: '/cards/$oracleId'
      fullPath: '/cards/$oracleId'
      preLoaderRoute: typeof CardsOracleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cards/$oracleId/$scryfallId': {
      id: '/cards/$oracleId/$scryfallId'
      path: '/$scryfallId'
      fullPath: '/cards/$oracleId/$scryfallId'
      preLoaderRoute: typeof CardsOracleIdScryfallIdRouteImport
      parentRoute: typeof CardsOracleIdRoute
    }
  }
}

interface CardsOracleIdRouteChildren {
  CardsOracleIdScryfallIdRoute: typeof CardsOracleIdScryfallIdRoute
}

const CardsOracleIdRouteChildren: CardsOracleIdRouteChildren = {
  CardsOracleIdScryfallIdRoute: CardsOracleIdScryfallIdRoute,
}

const CardsOracleIdRouteWithChildren = CardsOracleIdRoute._addFileChildren(
  CardsOracleIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CardsOracleIdRoute: CardsOracleIdRouteWithChildren,
  CardsIndexRoute: CardsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
